import { User, Channel } from './types';

export const currentUser: User = {
  id: 'u1',
  name: 'Andi Pratama',
  avatar: '👨‍💻',
  status: 'online',
  role: 'Full Stack Developer',
};

export const users: User[] = [
  currentUser,
  {
    id: 'u2',
    name: 'Siti Rahayu',
    avatar: '👩‍💼',
    status: 'online',
    role: 'Project Manager',
  },
  {
    id: 'u3',
    name: 'Budi Santoso',
    avatar: '👨‍🎨',
    status: 'away',
    role: 'UI/UX Designer',
  },
  {
    id: 'u4',
    name: 'Dewi Lestari',
    avatar: '👩‍🔬',
    status: 'online',
    role: 'Data Analyst',
  },
  {
    id: 'u5',
    name: 'Rizky Hidayat',
    avatar: '👨‍🔧',
    status: 'offline',
    role: 'DevOps Engineer',
  },
  {
    id: 'u6',
    name: 'Maya Putri',
    avatar: '👩‍💻',
    status: 'busy',
    role: 'Frontend Developer',
  },
  {
    id: 'u7',
    name: 'Fajar Nugroho',
    avatar: '👨‍📊',
    status: 'online',
    role: 'Backend Developer',
  },
  {
    id: 'u8',
    name: 'Lina Marlina',
    avatar: '👩‍🏫',
    status: 'offline',
    role: 'QA Engineer',
  },
];

export const initialChannels: Channel[] = [
  {
    id: 'ch1',
    name: 'umum',
    description: 'Channel untuk diskusi umum tim',
    type: 'public',
    unreadCount: 3,
    members: ['u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8'],
    messages: [
      {
        id: 'm1',
        userId: 'u2',
        content: 'Selamat pagi semua! 🌅 Jangan lupa standup meeting jam 10 ya.',
        timestamp: new Date(2024, 0, 15, 8, 30),
        reactions: [{ emoji: '👍', users: ['u1', 'u3', 'u4'] }],
      },
      {
        id: 'm2',
        userId: 'u3',
        content: 'Siap! Saya sudah siapkan mockup baru untuk halaman dashboard.',
        timestamp: new Date(2024, 0, 15, 8, 35),
      },
      {
        id: 'm3',
        userId: 'u1',
        content: 'Mantap! Nanti saya review setelah standup ya.',
        timestamp: new Date(2024, 0, 15, 8, 40),
        reactions: [{ emoji: '🔥', users: ['u3'] }],
      },
      {
        id: 'm4',
        userId: 'u4',
        content: 'Saya sudah selesai analisis data user behavior bulan lalu. Mau saya share hasilnya?',
        timestamp: new Date(2024, 0, 15, 9, 0),
      },
      {
        id: 'm5',
        userId: 'u2',
        content: 'Boleh banget! Share di channel #data-analytics ya supaya terdokumentasi.',
        timestamp: new Date(2024, 0, 15, 9, 5),
        reactions: [{ emoji: '✅', users: ['u4'] }],
      },
      {
        id: 'm6',
        userId: 'u6',
        content: 'Guys, ada yang bisa bantu review PR #245? Sudah saya update sesuai feedback kemarin.',
        timestamp: new Date(2024, 0, 15, 9, 15),
      },
      {
        id: 'm7',
        userId: 'u7',
        content: 'Saya bantu review ya, nanti siang saya cek.',
        timestamp: new Date(2024, 0, 15, 9, 20),
      },
    ],
  },
  {
    id: 'ch2',
    name: 'frontend',
    description: 'Diskusi development frontend',
    type: 'public',
    unreadCount: 1,
    members: ['u1', 'u3', 'u6', 'u7'],
    messages: [
      {
        id: 'm8',
        userId: 'u6',
        content: 'Saya sudah migrate komponen ke React 18. Semua test pass! 🎉',
        timestamp: new Date(2024, 0, 15, 10, 0),
        reactions: [{ emoji: '🎉', users: ['u1', 'u7'] }],
      },
      {
        id: 'm9',
        userId: 'u1',
        content: 'Nice! Apakah ada breaking changes yang perlu diperhatikan?',
        timestamp: new Date(2024, 0, 15, 10, 5),
      },
      {
        id: 'm10',
        userId: 'u6',
        content: 'Ada sedikit di useEffect cleanup, tapi sudah saya handle. Nanti saya buat dokumentasinya.',
        timestamp: new Date(2024, 0, 15, 10, 10),
      },
      {
        id: 'm11',
        userId: 'u3',
        content: 'Design system sudah saya update di Figma. Komponen baru: Date Picker dan Multi Select.',
        timestamp: new Date(2024, 0, 15, 11, 0),
      },
    ],
  },
  {
    id: 'ch3',
    name: 'backend',
    description: 'Diskusi development backend & API',
    type: 'public',
    unreadCount: 0,
    members: ['u1', 'u5', 'u7'],
    messages: [
      {
        id: 'm12',
        userId: 'u7',
        content: 'API endpoint untuk user analytics sudah deploy ke staging.',
        timestamp: new Date(2024, 0, 15, 9, 30),
      },
      {
        id: 'm13',
        userId: 'u5',
        content: 'CI/CD pipeline sudah saya optimasi. Build time turun dari 8 menit ke 3 menit! ⚡',
        timestamp: new Date(2024, 0, 15, 10, 0),
        reactions: [{ emoji: '⚡', users: ['u1', 'u7'] }, { emoji: '🚀', users: ['u1'] }],
      },
      {
        id: 'm14',
        userId: 'u1',
        content: 'Keren! Database migration untuk v2.0 juga sudah siap ya?',
        timestamp: new Date(2024, 0, 15, 10, 15),
      },
    ],
  },
  {
    id: 'ch4',
    name: 'design',
    description: 'Diskusi desain UI/UX',
    type: 'public',
    unreadCount: 2,
    members: ['u3', 'u6', 'u2'],
    messages: [
      {
        id: 'm15',
        userId: 'u3',
        content: 'Saya sudah finalize design untuk halaman settings. Ada 3 opsi layout, mau lihat?',
        timestamp: new Date(2024, 0, 15, 11, 0),
      },
      {
        id: 'm16',
        userId: 'u2',
        content: 'Tentu! Share di sini aja, biar kita diskusi bareng.',
        timestamp: new Date(2024, 0, 15, 11, 5),
      },
      {
        id: 'm17',
        userId: 'u3',
        content: 'Oke, saya pilih opsi B karena lebih clean dan konsisten dengan design system kita. 🎨',
        timestamp: new Date(2024, 0, 15, 11, 15),
        reactions: [{ emoji: '❤️', users: ['u2', 'u6'] }],
      },
    ],
  },
  {
    id: 'ch5',
    name: 'data-analytics',
    description: 'Sharing data dan analisis',
    type: 'public',
    unreadCount: 0,
    members: ['u4', 'u2', 'u7'],
    messages: [
      {
        id: 'm18',
        userId: 'u4',
        content: 'Report bulanan sudah siap. Key findings:\n1. User engagement naik 23%\n2. Retention rate stabil di 78%\n3. Feature adoption masih rendah di modul reporting',
        timestamp: new Date(2024, 0, 15, 11, 30),
        reactions: [{ emoji: '📊', users: ['u2'] }],
      },
      {
        id: 'm19',
        userId: 'u2',
        content: 'Thanks Dewi! Bisa tolong prepare presentasi untuk meeting dengan stakeholder minggu depan?',
        timestamp: new Date(2024, 0, 15, 11, 35),
      },
    ],
  },
  {
    id: 'ch6',
    name: 'random',
    description: 'Ngobrol santai & fun',
    type: 'public',
    unreadCount: 5,
    members: ['u1', 'u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8'],
    messages: [
      {
        id: 'm20',
        userId: 'u5',
        content: 'Ada yang mau join futsal Jumat sore? 🏃‍♂️⚽',
        timestamp: new Date(2024, 0, 15, 12, 0),
        reactions: [{ emoji: '🙋‍♂️', users: ['u1', 'u7'] }],
      },
      {
        id: 'm21',
        userId: 'u4',
        content: 'Count me in! Jam berapa?',
        timestamp: new Date(2024, 0, 15, 12, 5),
      },
      {
        id: 'm22',
        userId: 'u5',
        content: 'Jam 5 sore, tempat biasa. Lapangan ABC di Sudirman.',
        timestamp: new Date(2024, 0, 15, 12, 10),
      },
      {
        id: 'm23',
        userId: 'u8',
        content: 'Rekomendasi podcast tech yang bagus apa ya? Lagi cari yang tentang system design.',
        timestamp: new Date(2024, 0, 15, 12, 30),
      },
      {
        id: 'm24',
        userId: 'u1',
        content: 'Coba "System Design Primer" atau "Software Engineering Daily". Dua-duanya bagus! 🎧',
        timestamp: new Date(2024, 0, 15, 12, 35),
        reactions: [{ emoji: '👍', users: ['u8'] }],
      },
    ],
  },
];

// Auto-reply responses for simulation
export const autoReplies: Record<string, string[]> = {
  ch1: [
    'Noted, terima kasih infonya! 👍',
    'Siap, saya akan跟进 hal ini.',
    'Oke, nanti kita bahas di meeting ya.',
    'Mantap! Keep up the good work! 🔥',
    'Bisa tolong detail lebih lanjut?',
  ],
  ch2: [
    'Saya sudah cek, looks good! ✅',
    'Coba pakai approach yang baru, lebih clean.',
    'PR sudah saya approve 👌',
    'Nice work! Component-nya reusable banget.',
    'Ada issue di responsive, bisa cek?',
  ],
  ch3: [
    'API response time sudah optimal, < 200ms.',
    'Database query sudah di-optimize.',
    'Endpoint baru sudah ready di staging.',
    'Coba cek documentation di Swagger ya.',
    'Migration script sudah saya prepare.',
  ],
  ch4: [
    'Design-nya keren! Saya suka color palette-nya 🎨',
    'Mungkin spacing-nya bisa ditambah sedikit.',
    'Sudah sesuai brand guideline 👌',
    'Saya prefer opsi yang kedua.',
    'Typography-nya sudah perfect!',
  ],
  ch5: [
    'Data-nya menarik! Bisa deep dive lebih lanjut?',
    'Insight ini berguna banget untuk strategi kita.',
    'Tolong export ke PDF ya untuk report.',
    'Trend-nya positif, good job! 📈',
    'Perlu segmentasi lebih detail.',
  ],
  ch6: [
    'Haha setuju banget! 😂',
    'Wah asik! Count me in! 🙌',
    'Ada rekomendasi tempat makan siang?',
    'Weekend ini ada yang mau hangout?',
    'Kopi dulu yuk ☕',
  ],
};
